# Generated by Django 4.0.2 on 2022-02-20 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_item_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='itemimage',
            field=models.CharField(default='https://png.pngtree.com/element_our/20200702/ourmid/pngtree-vector-illustration-knife-and-fork-western-food-plate-image_2283844.jpg', max_length=1000),
        ),
    ]
